build:
  image: default-bionic
  environment:
    php: 8.2
  project_setup:
    override:
      - 'true'
  tests:
    override:
      - php-scrutinizer-run
      - command: phpcs-run --standard=phpcs.xml src/
checks:
  php: true
filter:
  dependency_paths:
    - "vendor/"
